name: Main
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'test/**'
      - '.github/**'
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint
        run: make quality
      - name: Build
        run: |
          npm i ./web
          make build
      - name: Test
        run: |
          make test