on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  
name: Release
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          target-branch: ${{ github.ref_name }}
      - uses: ./.github/actions/setup
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: "1.22.x"
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm i ./web
          make VERSION="${{ steps.release.outputs.tag_name }}" build
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./out/tinytune_linux_amd64
          gh release create latest --notes "#[${{ steps.release.outputs.tag_name }}](https://github.com/alxarno/tinytune/releases/tag/${{ steps.release.outputs.tag_name }})"
          gh release upload latest ./out/tinytune_linux_amd64