on:
  push:
    branches:
      - 1.x
  
permissions:
  contents: write
  pull-requests: write
  
name: release-please
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          target-branch: ${{ github.ref_name }}
      - uses: alxarno/tinytune/.github/workflows/_env.yml@main
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: '1.22.x'
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm i ./web
          make build
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./out/tinytune_linux_amd64